# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Test

on:
  push:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: "20"
          distribution: "temurin"
          cache: maven

      - name: Setting up secrets.properties
        env:
          INTEGRATION_STORAGE_ACCOUNT_KEY: ${{ secrets.IntegrationStorageAccountKey }}
        run: |
          cd ./src/test/resources/scripts/
          chmod +x create-secrets.bash
          ./create-secrets.bash --storage-account-key "$INTEGRATION_STORAGE_ACCOUNT_KEY"
          cd -
        shell: bash

      - name: Build and test
        run: mvn --batch-mode --update-snapshots verify -Pcoverage

      # Uses: https://github.com/marketplace/actions/jacoco-reporter
      - name: Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: target/site/jacoco/jacoco.xml
          coverage_report_name: Code Coverage
          coverage_report_title: Code Coverage
          github_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 70
          fail_below_threshold: true
          publish_only_summary: false

      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

      - name: Delete integration storage account containers
        env:
          INTEGRATION_STORAGE_ACCOUNT_KEY: ${{ secrets.IntegrationStorageAccountKey }}
        run: |
          chmod +x ./src/test/resources/scripts/delete-integration-storage-account-containers.bash
          ./src/test/resources/scripts/delete-integration-storage-account-containers.bash "$INTEGRATION_STORAGE_ACCOUNT_KEY"
        shell: bash

permissions:
  contents: read
  pull-requests: write
  checks: write
